### ISSUE TITLE
updateFile and updateFileSync support

### ISSUE THREAD

**Issue by manidlou** [jprichardson/node-jsonfile#75] opened 2017-03-20 02:54 UTC
Please let me know if you think it is reasonable to add these two functions or no need for them :smile: 

- `updateFile(filepath, obj, cb)`
- `updateFileSync(filepath, obj)`

They read the file, update the file contents with `obj` using something like `Object.assign()`, then write back the updated contents to the same file.

**Comment by RyanZim** [comment] 2017-04-25 14:10
Related/duplicate of https://github.com/jprichardson/node-jsonfile/issues/52.

**Closed** 2017-04-25 16:50 UTC
Labels: enhancement
