### ISSUE TITLE
Getting valid json after append it

### ISSUE THREAD

**Issue by Rundik** [jprichardson/node-jsonfile#106] opened 2018-04-21 13:17 UTC
If I append json with the code from documentation, thet looks like this:
```
jsonfile.writeFile(file, obj, {flag: 'a'}, function (err) {
  console.error(err)
})
```
I don't get a valid json file, becose it just appends in the file, but not in json object in it.
I can just read the json file, push objects in it and then write back.
But this is a library to work with json, so there must be a better solution, isn't it?

**Comment by RyanZim** [comment] 2018-04-21 14:04
Basially a dupe of https://github.com/jprichardson/node-jsonfile/issues/52

**Closed by RyanZim** 2018-04-21 14:04 UTC
