### ISSUE TITLE
Typescript "typings" support?

### ISSUE THREAD

**Issue by tatemz** [jprichardson/node-jsonfile#71] opened 2017-02-16 04:39 UTC
Any intention to add a `@types/jsonfile` declaration module?

https://www.npmjs.com/~types

**Comment by Frank3K** [comment] 2017-04-23 17:07
Duplicate of #57?

**Comment by jprichardson** [comment] 2017-04-24 03:17
No, but I'd gladly link the README to someone else who did it.

**Closed by jprichardson** 2017-04-24 03:17 UTC
