### ISSUE TITLE
Unexpected end of json input file on read

### ISSUE THREAD

**Issue by giper45** [jprichardson/node-jsonfile#79] opened 2017-05-11 11:10 UTC
Sometimes jsonfile gives me: 
``` Unexpected end of JSON input ```
on a correct file. 
If I try to read more times I have almost always the correct parsing, but sometimes it gives this error.  

I'm not able to understand when it happens, anyway as soon as I can I'll try some stress test on some file with this behavior ... for example, a type of file is this: 

```json
[ {"repoName":"DSP_Projects","labName":"dsp 1","state":"STOPPED"},
  {"repoName":"test_repo","labName":"networkTestDir","state":"STOPPED"},
  {"repoName":"test_repo","labName":"networkTestDir2","state":"STOPPED"},
  {"repoName":"test_repo","labName":"runningDelete","state":"RUNNING"},
  {"repoName":"test_repo","labName":"newLab","state":"STOPPED"},
  {"repoName":"test_repo","labName":"toDelete","state":"STOPPED"},
  {"repoName":"test_repo","labName":"anotherNetwork","state":"STOPPED"},
  {"repoName":"test_repo","labName":"existentLab","state":"NO_NETWORK"},
  {"repoName":"test_repo","labName":"toEditLab","state":"STOPPED"},
  {"repoName":"test_repo","labName":"MITM","state":"STOPPED"},
  {"repoName":"DSP_Projects","labName":"first","state":"STOPPED"},
  {"repoName":"DSP_Projects","labName":"second","state":"STOPPED"},
  {"repoName":"actions_test_repo","labName":"TelnetClientSniffing_1","state":"STOPPED"},
  {"repoName":"actions_test_repo","labName":"ErrorSameSubnet","state":"STOPPED"},
  {"repoName":"actions_test_repo","labName":"ErrorSamePort","state":"STOPPED"}
]
```  
but it happens even with files previously written with jsonfile.

**Comment by jprichardson** [comment] 2017-05-11 13:36
Are you trying to read the file in a different process than where it's being written?

**Comment by giper45** [comment] 2017-05-11 14:27
Well, It's occurred often when I tried to write on "beforeEach() function" and read in the it()  function during a test so it could be a write / read problem. When I tried the json write on global "before()" function  it doesn't happen (or it happens very rarely). Anyway, this occurred yesterday on other code, I think it was only read code, but not sure... I've to check if there is some write / file order issue also in that code.

**Comment by giper45** [comment] 2017-05-11 14:28
Eventually I'll do some test of read / write loops in order to understand what happens !

**Comment by jprichardson** [comment] 2017-05-11 14:36
Why not just use the sync methods since this is for tests?

**Comment by giper45** [comment] 2017-05-11 18:12
Thanks @jprichardson , but It's already with sync methods :( ... And I use also in my app with aynch methods and sometimes it happens...  Anyway,  by inserting some console.log in the write and read sync methods: 
```
I M WRITING
I M READING
create DSP
I M READING
I M READING
I M READING
I M READING
I M READING
I M READING
I M READING
I M READING
I M READING
I M READING
    1) Should change configuration file
I M READING
I M READING
I M READING => here the json end input error
```
It doesn't seem to be a concurrency issue. Now I see a little to understand what is the possible issue, and what is the difference between the use of beforeEach() and before() so maybe I can understand better what happens.

**Comment by giper45** [comment] 2017-05-11 18:39
It seems to be a problem in fs.readFileSync; with those debug lines: 
```javascript
  var content = fs.readFileSync(file, options)
  console.log(content);
  content = stripBom(content)
  console.log('content:');
  console.log(content);

```
The result is: 
```

<Buffer 7b 22 6e 61 6d 65 22 3a 22 74 65 73 74 5f 72 65 70 6f 22 2c 22 6d 61 69 6e 44 69 72 22 3a 22 44 53 50 5f 54 45 53 54 49 4e 47 5f 49 4e 53 54 41 4c 4c ... >
content:
{"name":"test_repo","mainDir":"DSP_TESTING_INSTALLATION_DIRECTORY","githubURL":"https://github.com/giper45/personalTestRepo.git"}

<Buffer 7b 22 6e 61 6d 65 22 3a 22 74 65 73 74 5f 72 65 70 6f 22 2c 22 6d 61 69 6e 44 69 72 22 3a 22 44 53 50 5f 54 45 53 54 49 4e 47 5f 49 4e 53 54 41 4c 4c ... >
content:
{"name":"test_repo","mainDir":"DSP_TESTING_INSTALLATION_DIRECTORY","githubURL":"https://github.com/giper45/personalTestRepo.git"}

<Buffer 7b 22 6e 61 6d 65 22 3a 22 74 65 73 74 5f 72 65 70 6f 22 2c 22 6d 61 69 6e 44 69 72 22 3a 22 44 53 50 5f 54 45 53 54 49 4e 47 5f 49 4e 53 54 41 4c 4c ... >
content:
{"name":"test_repo","mainDir":"DSP_TESTING_INSTALLATION_DIRECTORY","githubURL":"https://github.com/giper45/personalTestRepo.git"}

<Buffer 7b 22 6e 61 6d 65 22 3a 22 74 65 73 74 5f 72 65 70 6f 22 2c 22 6d 61 69 6e 44 69 72 22 3a 22 44 53 50 5f 54 45 53 54 49 4e 47 5f 49 4e 53 54 41 4c 4c ... >
content:
{"name":"test_repo","mainDir":"DSP_TESTING_INSTALLATION_DIRECTORY","githubURL":"https://github.com/giper45/personalTestRepo.git"}

<Buffer >
content:

-->here the error : empty string 
```
It seems that for some reason fs.readFileSync returns empty string after repeated calls... I should check if this behavior is present also outside of jsonfile library (so it's a fs issue) or there is some flag / condition to set/check before the read but I don't have time to debug this now sorry ... eventually I'll try to ask to fs github page

**Comment by rohmanhm** [comment] 2017-09-23 14:49
Got same issue here.

**Comment by MadSummer** [comment] 2017-12-05 07:36
Got same issue here.

**Comment by Zechtitus** [comment] 2017-12-07 15:51
MAy as well join the list... seeing the same issue as well.

**Comment by ShujaathKhan** [comment] 2017-12-30 05:19
Emty JSON file thows **Unexpected end of JSON input**

**Comment by RyanZim** [comment] 2020-01-30 15:26
I'm going to close this out, since we've never gotten a clear reproducible case of this. Happy to reopen if we have something to go on.

**Closed by RyanZim** 2020-01-30 15:26 UTC
